# Generated by Django 3.2.11 on 2022-01-28 10:07

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сериала')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('rating', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Рейтинг кинопоиска')),
                ('serialYearStart', models.IntegerField(max_length=4, verbose_name='Дата выхода')),
                ('serialYearEnd', models.IntegerField(max_length=4, verbose_name='Дата закрытия')),
                ('countries', models.CharField(max_length=255, verbose_name='Страна')),
                ('serialLinkKino', models.CharField(blank=True, max_length=255, verbose_name='URL в Кинопоиске')),
                ('posterLink', models.CharField(blank=True, max_length=255, verbose_name='URL Постера')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('posterImage', models.ImageField(blank=True, upload_to='serials/', verbose_name='Постер')),
                ('genres', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Serial_info',
            fields=[
                ('serial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='serials.serial', verbose_name='Serial_id')),
                ('MySeriadescription', models.TextField(blank=True, verbose_name='Описание сериала')),
                ('MySeriarating', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Рейтинг MySeria')),
                ('LastSerianame', models.CharField(blank=True, max_length=255, verbose_name='Последняя серия')),
                ('LastSeriaurl', models.CharField(blank=True, max_length=255, verbose_name='URL последней серии')),
                ('LastSeriavoice', models.CharField(blank=True, max_length=255, verbose_name='Озвучки')),
            ],
        ),
    ]
