# Generated by Django 3.2.11 on 2022-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='serialYearEnd',
            field=models.IntegerField(verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='serialYearStart',
            field=models.IntegerField(verbose_name='Дата выхода'),
        ),
    ]
